=== m-jumpi/xml/lessons_DTD.dtd
<!ELEMENT TimeTable (cource+)>
<!ELEMENT cource (name, teacher, duration, startdate, enddate)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT teacher (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT startdate (#PCDATA)>
<!ELEMENT enddate (#PCDATA)>

=== m-jumpi/xml/lessons.xml
<?xml version = "1.0" encoding ="utf-8"?>
<!-- <!DOCTYPE TimeTable SYSTEM "lessons_DTD.dtd"> -->
<?xml-model href="lessons_XML.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<TimeTable>
    <cource>
        <name>CSharp</name>
        <teacher>Teacher #1</teacher>
        <duration>50</duration>
        <startdate>01-01-2022</startdate>
        <enddate>01-02-2022</enddate>
    </cource>
    <cource>
        <name>ADO</name>
        <teacher>Teacher #2</teacher>
        <duration>40</duration>
        <startdate>01-03-2022</startdate>
        <enddate>01-04-2022</enddate>
    </cource>
    <cource>
        <name>WinForms</name>
        <teacher>Teacher #3</teacher>
        <duration>60</duration>
        <startdate>01-05-2022</startdate>
        <enddate>01-06-2022</enddate>
    </cource>
    <cource>
        <name>T-SQL</name>
        <teacher>Teacher #4</teacher>
        <duration>50</duration>
        <startdate>01-07-2022</startdate>
        <enddate>01-08-2022</enddate>
    </cource>
    <cource>
        <name>Databases</name>
        <teacher>Teacher #5</teacher>
        <duration>40</duration>
        <startdate>01.09.2022</startdate>
        <enddate>20-09-2022</enddate>
    </cource>
</TimeTable>
